In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv("undersampled_data.csv")
df

User  Card    Year  Month   Day   Amount             UseChip  \
0     1750.0   0.0  2015.0    7.0  16.0   $21.42   Swipe Transaction   
1     1959.0   1.0  2016.0    5.0   5.0   $76.99    Chip Transaction   
2      182.0   2.0  2012.0   11.0  23.0    $2.19   Swipe Transaction   
3      458.0   2.0  2019.0    5.0  15.0   $45.73    Chip Transaction   
4     1949.0   0.0  2018.0    1.0   4.0    $1.25    Chip Transaction   
...      ...   ...     ...    ...   ...      ...                 ...   
1739   309.0   1.0  2008.0    7.0   1.0  $142.44   Swipe Transaction   
1740   731.0   0.0  2011.0    9.0  21.0   $33.29  Online Transaction   
1741  1995.0   1.0  2014.0    2.0   9.0    $0.93  Online Transaction   
1742  1075.0   0.0  2016.0   11.0  27.0   $12.22    Chip Transaction   
1743   264.0   1.0  2020.0    2.0   1.0   $86.36    Chip Transaction   

                   MerchantName MerchantCity MerchantState           Zip  \
0               Lukass Theaters       Tiffin            OH  44883.000000   
1              Jadens Wholesale    Lancaster            CA  93535.000000   
2           Supermarket Chain 3      Houston            TX  77096.000000   
3           Supermarket Chain 3        Flint            MI  48532.000000   
4     Convenience Store Chain 1     Brooklyn            NY  11213.000000   
...                         ...          ...           ...           ...   
1739  Amaris Istanbul Wholesale     Istanbul        Turkey  51694.676895   
1740         Department Store 9       ONLINE            CA  51694.676895   
1741        Department Store 10       ONLINE            CA  51694.676895   
1742             Diaz Ale House  Simi Valley            CA  93065.000000   
1743           Eddies Wholesale   Georgetown        Guyana  51694.676895   

         MCC target  
0     7832.0     No  
1     5300.0     No  
2     5411.0     No  
3     5411.0     No  
4     5499.0     No  
...      ...    ...  
1739  5310.0    Yes  
1740  5311.0    Yes  
1741  5311.0    Yes  
1742  5813.0    Yes  
1743  5310.0    Yes  

[1744 rows x 13 columns]

In [4]:
df["target"].value_counts()

target
No     872
Yes    872
Name: count, dtype: int64

In [5]:
df.isnull().sum()

User             0
Card             0
Year             0
Month            0
Day              0
Amount           0
UseChip          0
MerchantName     0
MerchantCity     0
MerchantState    0
Zip              0
MCC              0
target           0
dtype: int64

In [6]:
df['Amount'] = df['Amount'].replace({'\$': '', ',': ''}, regex=True).astype(float)

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
col = ['UseChip', 'MerchantName', 'MerchantCity', 'MerchantState','target']
for i in col:
    df[i] = le.fit_transform(df[i]).astype(int)

In [8]:
independent=df[['Year', 'Month', 'UseChip','Amount',
       'MerchantName', 'MerchantCity', 'MerchantState','MCC']]

dependent=df[['target']]
independent

Year  Month  UseChip  Amount  MerchantName  MerchantCity  \
0     2015.0    7.0        2   21.42           383           522   
1     2016.0    5.0        0   76.99           318           270   
2     2012.0   11.0        2    2.19           529           230   
3     2019.0    5.0        0   45.73           529           171   
4     2018.0    1.0        0    1.25           153            68   
...      ...    ...      ...     ...           ...           ...   
1739  2008.0    7.0        2  142.44            52           240   
1740  2011.0    9.0        1   33.29           190           387   
1741  2014.0    2.0        1    0.93           180           387   
1742  2016.0   11.0        0   12.22           191           502   
1743  2020.0    2.0        0   86.36           209           189   

      MerchantState     MCC  
0                45  7832.0  
1                 6  5300.0  
2                55  5411.0  
3                31  5411.0  
4                44  5499.0  
...             ...     ...  
1739             56  5310.0  
1740              6  5311.0  
1741              6  5311.0  
1742              6  5813.0  
1743             16  5310.0  

[1744 rows x 8 columns]

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=1/3,random_state=42)

In [10]:
X_test.shape

(582, 8)

In [11]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators= 100, criterion="entropy")
classifier=classifier.fit(X_train,Y_train.values.ravel())

In [12]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test.values.ravel(),y_pred)

In [14]:
cm

array([[275,  15],
       [ 33, 259]], dtype=int64)

In [15]:
from sklearn.metrics import classification_report
clf_report=classification_report(Y_test.values.ravel(),y_pred)

In [16]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.89      0.95      0.92       290
           1       0.95      0.89      0.92       292

    accuracy                           0.92       582
   macro avg       0.92      0.92      0.92       582
weighted avg       0.92      0.92      0.92       582



In [17]:
Year=int(input())
Month=int(input())
UseChip=int(input())
Amount=int(input())
MerchantName=int(input())
MerchantCity=int(input())
MerchantState=int(input())
mcc=int(input())

2013
1
2
193
422
520
18
5921


In [18]:
future_prediction=classifier.predict([[Year,Month,UseChip,Amount,MerchantName,MerchantCity,MerchantState,mcc]])
future_prediction


array([1])

In [19]:
import joblib

# Assuming you have already trained a model named 'classifier'
# Save the model to a file
joblib.dump(classifier, 'frauddetection.pkl')

['frauddetection.pkl']